let name = 'Ana';
let age = 30;
let isUkrainian = true;
let occupation = null;
let testUndefined = console.log(name);
console.log(typeof name);
console.log(age);
console.log(typeof age);
console.log(isUkrainian);
console.log(typeof isUkrainian);
console.log(occupation);
console.log(typeof occupation);
console.log(testUndefined);
console.log(typeof testUndefined);
